<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Wednesday 20th of November 2013 02:56:23 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://www.oneoweb.com/modules/partage/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array ( 
				"enabled" => true 
			),

			"Yahoo" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "dj0yJmk9TEMydm9pMDZ6RTNuJmQ9WVdrOWFYUlVUV3M1TXpRbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD0zMA--", "secret" => "aa022f22465f77ba58b71a2889b13df1d2958fb7" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "784593522102.apps.googleusercontent.com", "secret" => "wAoTIYRn_9cbouJXgYigRZtr" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "465622970223733", "secret" => "82095fc3da435d7b1d875d1759e1a829" )
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
