USE [RAMEX]
GO

/****** Object:  Table [dbo].[Compteur]    Script Date: 28/12/2020 09:32:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Compteur](
	[mois] [char](4) NOT NULL,
	[compteur] [numeric](19, 0) NOT NULL,
 CONSTRAINT [PK_Compteur] PRIMARY KEY CLUSTERED
(
	[mois] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
