USE [RAMEX]
GO

/****** Object:  Table [dbo].[COUNTER]    Script Date: 28/12/2020 09:33:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COUNTER](
	[compteur_cd] [char](4) NOT NULL,
	[compteur] [numeric](18, 0) NULL,
 CONSTRAINT [PK_COUNTER] PRIMARY KEY CLUSTERED
(
	[compteur_cd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
